### ISSUE TITLE
there are many problems

### ISSUE THREAD

**Issue by naah69** [nacos-group/nacos-sdk-python#1]
i use 1.0.0.GA nacos and  this plugin.

the first problem is that `add_naming_instance` will throw exception(HTTP 400),because the default value of paramter `metadata` is None,it make the request be 400.

now,the second problem is service will be down after some seconds

**Comment by bowenliang123** [comment]
+1

**Comment by silaslxy** [comment]
+1

**Comment by samandqq** [comment]
The develop branch has been fixed it and will be merged into the master branch later
