### ISSUE TITLE
nacos 注册上去不健康

### ISSUE THREAD

**Issue by rlacjfjin** [nacos-group/nacos-sdk-python#104]
你好:

我注册nacos的时候参数设置如下：
client.add_naming_instance("nacos_name", ip, port, "DEFAULT", 1, None, True, True, False)
我看了函数的参数是这样的：
add_naming_instance(self, service_name, ip, port, cluster_name=None, weight=1.0, metadata=None,
                            enable=True, healthy=True, ephemeral=True,group_name=DEFAULT_GROUP_NAME)

当我设置ephemeral=True 的时候，过一段时间自己会断掉，如果设为False就不会断，所以后面写成False.

现在的问题是：

<html>
<body>

 集群数目 | 实例数 | 健康实例数 | 触发保护阈值 
-- | -- | -- | -- | -- | --
  1 | 1 | 0 | true

</body>
</html>

也就是说，健康实例数为0，正常应该是1才对吧？ 

能帮忙看一下吗？
谢谢

**Comment by lvhaidong** [comment]
你要不停的发送心跳包。注册服务和心跳时俩个接口的。 注册服务成功后，定时发送心跳就可以了

**Comment by rlacjfjin** [comment]
> 

谢谢，
我已经通过send_heartbeat来检测心跳，每隔5秒检测一次，然后检测失败了就重新注册上去的方式。
目前来看是没有问题的！
