### ISSUE TITLE
我在使用Django框架的时候如何动态获取配置文件新配置

### ISSUE THREAD

**Issue by TobyXi1997** [nacos-group/nacos-sdk-python#109]
我在使用Django框架的时候想要动态获取最新的配置文件信息，我是应该使用add_config_watchers（）这种方法吗，回调函数应该怎么写

**Comment by fengxiao2019** [comment]
回调函数传的参数结构：
params = {
                "data_id": data_id,
                "group": group,
                "namespace": namespace,
                "raw_content": content,
                "content": plain_content,
            }
回调函数，怎么写？看你怎么处理配置数据,如果的你的data_id 是唯一的，可以这么处理：
```
FuxiConfigData = {}
def update_config(val):
    FuxiConfigData[val['data_id']] = val['content']
```
