### ISSUE TITLE
有没有大佬整个支持nacos2.x的版本啊

### ISSUE THREAD

**Issue by CarolsYang** [nacos-group/nacos-sdk-python#121]
希望有支持2.x的版本

**Comment by chenhao26-nineteen** [comment]
他应该指的是Nacos Client支持2.x？现在客户端应该都是基于open API，暂时还不支持grpc

**Comment by CarolsYang** [comment]
不需要支持grpc啊，我们之前升级2.x，服务注册上去一会就红了，挂不上去，是2.x的心跳机制不一样吗

**Comment by CarolsYang** [comment]
> 他应该指的是Nacos Client支持2.x？现在客户端应该都是基于open API，暂时还不支持grpc

不需要支持grpc啊，我们之前升级2.x，服务注册上去一会就红了，挂不上去，是2.x的心跳机制不一样吗

**Comment by LinkMaq** [comment]
同问：
python的 sdk注册到 2.x 版本的服务健康状态和注册状态会频繁的跳动。
其它像 java client 1.3.1 版本注册到 2.x 的服务状态比较问题。

**Comment by xinwangu** [comment]
> > 他应该指的是Nacos Client支持2.x？现在客户端应该都是基于open API，暂时还不支持grpc
> 
> 不需要支持grpc啊，我们之前升级2.x，服务注册上去一会就红了，挂不上去，是2.x的心跳机制不一样吗

请问现在有解决方案了吗

**Comment by flaymes** [comment]
请问有没有支持nacos 2.x的版本？

**Comment by xinwangu** [comment]
> 请问有没有支持nacos 2.x的版本？

现在应该还是没有官方的nacos 2.x的版本。
我注意到官方文档写到nacos 2.x仍然是兼容nacos 1.x的API的，所以封装了nacos 1.x的API， 只实现了注册，注销，发送心跳3个功能，全部使用V1版本的API，目前看正常。当时封装V2版本的API时，健康实例数一直不稳定，所以上述3个功能都改为了V1版本.

**Comment by boholder** [comment]
> 当时封装V2版本的API时，健康实例数一直不稳定，所以上述3个功能都改为了V1版本.

不知道是否是nacos server端的v2 api有问题，如果它有问题按说所有语言的sdk只要用v2版本api都有问题。。

然后搜到了原因，是注册服务提供的服务名不符合v2标准？

https://github.com/alibaba/nacos/issues/10448#issuecomment-1538178112

**Comment by CZJCC** [comment]
https://github.com/nacos-group/nacos-sdk-python/issues/175  欢迎投票

**Comment by CZJCC** [comment]
试试看这个版本 https://github.com/nacos-group/nacos-sdk-python?tab=readme-ov-file#nacos-sdk-python-v2
