### ISSUE TITLE
[BUG] 使用用户名和密码鉴权更新配置报错Insufficient Privilege

### ISSUE THREAD

**Issue by mangox** [nacos-group/nacos-sdk-python#135]
root casue:
该函数中_inject_auth_info 并未把username, password放到url中。

**Comment by sty1992928** [comment]
我也遇到了，最根本的原因应该是https://github.com/nacos-group/nacos-sdk-python/blob/master/nacos/client.py#L865
params的位置错了，导致往里面传的params都是None

**Comment by tthungry** [comment]
_inject_auth_info中不要进行params是否为空的判断，这样同时满足GET和POST调用
<         if self.username and self.password and params:
---
>         if self.username and self.password:

**Comment by mangox** [comment]
@tthungry 
我也是这么改的

**Comment by xuyooo** [comment]
版本0.1.14 修改判空和修改 publish_config 等方法的params参数位置后还是报错

**Comment by CallMeHFK** [comment]
@nacos-group 不打算fix下这个问题吗

> 我也遇到了，最根本的原因应该是https://github.com/nacos-group/nacos-sdk-python/blob/master/nacos/client.py#L865 params的位置错了，导致往里面传的params都是None

**Comment by CZJCC** [comment]
0.1.16 fixed
