### ISSUE TITLE
nacos2.x报错Insufficient Privilege

### ISSUE THREAD

**Issue by lemonl2** [nacos-group/nacos-sdk-python#137]
in add_naming_instance
    raise NacosException("Insufficient privilege.")
nacos.exception.NacosException: Insufficient privilege.

**Comment by lemonl2** [comment]
官方能不能修复一下这个问题

**Comment by AleutianXie** [comment]
遇到同样的问题，亟待官方修复

**Comment by giserd** [comment]
@lemonl2 @AleutianXie 我也遇到相同的注册问题，尝试把client的941行的resp = self._do_sync_req("/nacos/v1/ns/instance", None,None,params, self.default_timeout, "POST", "naming")改成resp = self._do_sync_req("/nacos/v1/ns/instance", None,params,None, self.default_timeout, "POST", "naming")试试

**Comment by Nthin** [comment]
> @lemonl2 @AleutianXie 我也遇到相同的注册问题，尝试把 client 的 941 行的 resp = self._do_sync_req ("/nacos/v1/ns/instance", None,None,params, self.default_timeout, "POST", "naming") 改成 resp = self._do_sync_req ("/nacos/v1/ns/instance", None,params,None, self.default_timeout, "POST", "naming") 试试

感谢，通过重写add_naming_instance方法，调换params和None的位置修复这个问题了

**Comment by giserd** [comment]
👍发自我的 iPhone在 2024年4月19日，18:19，JerryX ***@***.***> 写道：﻿

@lemonl2 @AleutianXie 我也遇到相同的注册问题，尝试把 client 的 941 行的 resp = self._do_sync_req ("/nacos/v1/ns/instance", None,None,params, self.default_timeout, "POST", "naming") 改成 resp = self._do_sync_req ("/nacos/v1/ns/instance", None,params,None, self.default_timeout, "POST", "naming") 试试

感谢，通过重写add_naming_instance方法，调换params和None的位置修复这个问题了

**Comment by CZJCC** [comment]
0.1.16 fixed
