### ISSUE TITLE
监听nacos服务，报错：ERROR:nacos.client:[do-pulling] exception HTTP Error 403:  occur, return empty list, waiting for recovery

### ISSUE THREAD

**Issue by lldfire** [nacos-group/nacos-sdk-python#138]
python：3.7
windos 10
nacos-sdk-python==0.1.12

使用add_config_watcher 方法报错如题错误，信息日志信息如下：
![image](https://github.com/nacos-group/nacos-sdk-python/assets/44776464/bbe59845-41ae-4047-a4a7-f405f3bbf426)

**Comment by Christings** [comment]
请问你解决了吗？我也遇到这个问题

**Comment by Jesse3692** [comment]
我也遇到这个问题

**Comment by Jesse3692** [comment]
> python：3.7 windos 10 nacos-sdk-python==0.1.12
> 
> 使用add_config_watcher 方法报错如题错误，信息日志信息如下： ![image](https://user-images.githubusercontent.com/44776464/254884402-bbe59845-41ae-4047-a4a7-f405f3bbf426.png)

https://pypi.org/project/nacos-python-sdk/  pypi上出了个0.2版本的，说是可以解决这个问题
![image](https://github.com/nacos-group/nacos-sdk-python/assets/24291671/3d3c2e5a-1be7-4380-9629-c8e058fd5e9d)

**Comment by Tompes** [comment]
同样，请问有解决办法吗

**Comment by jerryqzhang** [comment]
使用https://pypi.org/project/nacos-python-sdk/ 这个包，亲测可以解决监听时报403的问题
