### ISSUE TITLE
注册服务到nacos server的时候，怎么修改分组名称？

### ISSUE THREAD

**Issue by KunxiSun** [nacos-group/nacos-sdk-python#143]
我生成client对象后，注册到nacos里去，但是官方文档里没有说可以添加分组名称，添加上去后，全部都是‘DEFAULT_GROUP’
```python
    # 生成nacos的client对象
    client = NacosClient(server_addresses=app.config['NACOS_SERVER_ADDRESSES'],
                        namespace=app.config['NACOS_NAMESPACE_ID'])

    # 添加服务到nacos的命名空间里去
    client.add_naming_instance(service_name=app.config['SERVICE_NAME'],
        ip=app.config['SERVICE_IP'],
        port=app.config['SERVICE_PORT'],
        cluster_name=app.config['NACOS_SERVICE_CLUSTER_NAME']
    )

```
       
<img width="962" alt="image" src="https://github.com/nacos-group/nacos-sdk-python/assets/57077817/079b3fd8-df46-4674-ae0e-c8d1ec92aa71">

**Comment by xinwangu** [comment]
group_name字段是add_naming_instance方法的一个参数啊，直接传进去就行了。
另外想问一下：你们用的是2.X版本的nacos吗，这个SDK不支持2.X

**Comment by ZZZhsb** [comment]
> group_name字段是add_naming_instance方法的一个参数啊，直接传进去就行了。 另外想问一下：你们用的是2.X版本的nacos吗，这个SDK不支持2.X

这个功能应该支持2.X版本的吧，我看nacos的openapi文档是兼容1.x的

**Comment by xinwangu** [comment]
> > group_name字段是add_naming_instance方法的一个参数啊，直接传进去就行了。 另外想问一下：你们用的是2.X版本的nacos吗，这个SDK不支持2.X
> 
> 这个功能应该支持2.X版本的吧，我看nacos的openapi文档是兼容1.x的

nacos的openapi文档说的是nacos本身是支持他自己的1.x的接口的，但是python的SDK现在没有支持2.X的版本

**Comment by KunxiSun** [comment]
> > > group_name字段是add_naming_instance方法的一个参数啊，直接传进去就行了。 另外想问一下：你们用的是2.X版本的nacos吗，这个SDK不支持2.X
> > 
> > 
> > 这个功能应该支持2.X版本的吧，我看nacos的openapi文档是兼容1.x的
> 
> nacos的openapi文档说的是nacos本身是支持他自己的1.x的接口的，但是python的SDK现在没有支持2.X的版本

考不考虑我们自己更新一套兼容2.X版本的
