### ISSUE TITLE
how to resgister an instance?

### ISSUE THREAD

**Issue by Anyon123** [nacos-group/nacos-sdk-python#15]
I want to ask what is the process of registering an instance?
When I request this path  /nacos/v1/ns/instance by post method, it will report 500 error.
Shall I need to create a service firstly on the nacos server?

**Comment by Anyon123** [comment]
> You can use `nacos-python-sdk` to register an instance. Just use simple API as below，
> 
> ```python
>         import nacos
>         SERVER_HOST = "localhost"
> 
>         SERVER_PORT = 8848
>         SERVER_URI = SERVER_HOST + ":" + str(SERVER_PORT)
>         NAMESPACE = ""
>         client = nacos.NacosProxyClient(server_addresses=SERVER_URI,
>                                         namespace=NAMESPACE,
>                                         username=USERNAME,
>                                         password=PASSWORD)
>     
>         result = client.add_naming_instance(service_name="nacos-self-service", ip='localhost', port=8848,
>                                             cluster_name="nacos-py-cluster-name")
>     
>         print(result)
> ```

Thank you for helping.
Is it the `nacos-python-sdk` or `nacos-sdk-python`?
I tried `pip install nacos-python-sdk`. it didn't work.
But by `nacos-sdk-python`,  there is an error like this

Traceback (most recent call last):
  File "D:/01_work/2020/02_code/project6_nacos/optimzie_20200814/utils/tessst.py", line 21, in <module>
    client = nacos.NacosProxyClient(server_addresses=SERVER_URI,
AttributeError: module 'nacos' has no attribute 'NacosProxyClient'

**Comment by samandqq** [comment]
Please refer to test_add_naming_instance or test_add_naming_instance_with_dict_metadata in client_test.py

**Comment by Xarrow** [comment]
> > You can use `nacos-python-sdk` to register an instance. Just use simple API as below，
> > ```python
> >         import nacos
> >         SERVER_HOST = "localhost"
> > 
> >         SERVER_PORT = 8848
> >         SERVER_URI = SERVER_HOST + ":" + str(SERVER_PORT)
> >         NAMESPACE = ""
> >         client = nacos.NacosProxyClient(server_addresses=SERVER_URI,
> >                                         namespace=NAMESPACE,
> >                                         username=USERNAME,
> >                                         password=PASSWORD)
> >     
> >         result = client.add_naming_instance(service_name="nacos-self-service", ip='localhost', port=8848,
> >                                             cluster_name="nacos-py-cluster-name")
> >     
> >         print(result)
> > ```
> 
> Thank you for helping.
> Is it the `nacos-python-sdk` or `nacos-sdk-python`?
> I tried `pip install nacos-python-sdk`. it didn't work.
> But by `nacos-sdk-python`, there is an error like this
> 
> Traceback (most recent call last):
> File "D:/01_work/2020/02_code/project6_nacos/optimzie_20200814/utils/tessst.py", line 21, in
> client = nacos.NacosProxyClient(server_addresses=SERVER_URI,
> AttributeError: module 'nacos' has no attribute 'NacosProxyClient'

My fault.  This API just use in my develop branch and not release.  
You can reference at [https://github.com/nacos-group/nacos-sdk-python/blob/master/test/client_test.py](https://github.com/nacos-group/nacos-sdk-python/blob/master/test/client_test.py) in detail.

**Comment by Anyon123** [comment]
Thank youu it works
