### ISSUE TITLE
nacos 2.0+ python sdk

### ISSUE THREAD

**Issue by Jedore** [nacos-group/nacos-sdk-python#152]
:wave: 2024年了，开年有个计划：写一个支持完整nacos 2.0+功能的python sdk。
想看看究竟有多少小伙伴需要 python版 nacos2.0+ sdk ？ 

https://github.com/nacos-group/nacos-sdk-python/issues/87
https://github.com/nacos-group/nacos-sdk-python/issues/92
https://github.com/nacos-group/nacos-sdk-python/issues/97
https://github.com/nacos-group/nacos-sdk-python/issues/98
https://github.com/nacos-group/nacos-sdk-python/issues/121
https://github.com/nacos-group/nacos-sdk-python/issues/129

**Comment by m4kemoretime** [comment]
真是翘首以盼啊😄

**Comment by boholder** [comment]
请教下，达成“支持2.0+”目标的基线或者说验证目标都有哪些？最近一两个月后应该要用，如果知道基线的话我自己想办法糊一个先用着算了。。难受

**Comment by Jedore** [comment]
> 请教下，达成“支持2.0+”目标的基线或者说验证目标都有哪些？最近一两个月后工作上必须要用，如果知道基线的话我自己想办法糊一个先用着算了。。难受
> 
> FYI
> 
> * [有没有大佬整个支持nacos2.x的版本啊 #121 (comment)](https://github.com/nacos-group/nacos-sdk-python/issues/121#issuecomment-1911325737)
> * https://blog.csdn.net/m0_37892044/article/details/124167874#14nacos_18
> * https://nacos.io/zh-cn/docs/open-api.html
> 
> 自问自答，我们需要python服务和其他服务相互调用，所以最低程度在python侧应该实现:
> 
> 1. 注册
> 2. 注销
> 3. 心跳
> 4. 查询服务

@boholder 可以参考下rust https://github.com/nacos-group/nacos-sdk-rust

**Comment by boholder** [comment]
> @boholder 可以参考下rust https://github.com/nacos-group/nacos-sdk-rust

嘿，rust版本的作者也实现了用PyO3的python-binding版本，包括配置中心和服务发现功能，是用gRPC方式和nacos服务端通信的。让我实验下能否直接用。再次感谢信息。
https://github.com/opc-source/nacos-sdk-rust-binding-py
