### ISSUE TITLE
nacos2.2.3注册服务发送心跳服务列表中分组名称是DEFAULT_GROUP

### ISSUE THREAD

**Issue by AllenLee1** [nacos-group/nacos-sdk-python#154]
向nacos注册服务发送心跳，这个分组名称我指定了，但是他这里依旧显示DEFAULT_GROUP
<img width="776" alt="1" src="https://github.com/nacos-group/nacos-sdk-python/assets/167427709/310a1e11-1e1a-4350-88aa-bdf0b8512db0">
<img width="527" alt="2" src="https://github.com/nacos-group/nacos-sdk-python/assets/167427709/97da4596-bd93-4f32-9190-4bc5ecd18c50">

**Comment by CZJCC** [comment]
typo group_name
