### ISSUE TITLE
pypi.org版本更新

### ISSUE THREAD

**Issue by CallMeHFK** [nacos-group/nacos-sdk-python#157]
大佬们，pypi.org版本更新还是旧版的0.1.14，这个版本有[bug](https://github.com/nacos-group/nacos-sdk-python/issues/126),能不能更新下，万分感谢
![image](https://github.com/nacos-group/nacos-sdk-python/assets/43436802/2a2d480d-cf3c-4506-977e-cec89bd5b26c)

**Comment by CZJCC** [comment]
0.1.15 fixed

**Comment by CallMeHFK** [comment]
> 0.1.15 fixed

tks
