### ISSUE TITLE
/nacos/v2/cs/history/configs

### ISSUE THREAD

**Issue by li1356429504** [nacos-group/nacos-sdk-python#168]
{"timestamp":"2024-07-11T09:08:39.259+08:00","status":403,"error":"Forbidden","message":"user not found!","path":"/nacos/v2/cs/history/configs"}

**Comment by li1356429504** [comment]
`接口文档里，没有提供用户密码等传参`
![image](https://github.com/nacos-group/nacos-sdk-python/assets/44743066/33e06c90-f956-4815-b303-75020241c20a)

**Comment by CZJCC** [comment]
用户名密码在nacos.NacosClient时传入
