### ISSUE TITLE
望官方早日适配v2

### ISSUE THREAD

**Issue by al6nlee** [nacos-group/nacos-sdk-python#170]

**Comment by CZJCC** [comment]
WIP

**Comment by CZJCC** [comment]
https://github.com/nacos-group/nacos-sdk-python/issues/175  欢迎投票

**Comment by KunxiSun** [comment]
我自己写了个nacos的sdk，满足了v2版本nacos，但是仅包含一些基础功能。

v2版本nacos的开放接口里用了grpc（比如监听设置的更改）

**Comment by CZJCC** [comment]
试试看这个版本 https://github.com/nacos-group/nacos-sdk-python?tab=readme-ov-file#nacos-sdk-python-v2
