### ISSUE TITLE
【Nacos-SDK-Python官方】关于v2新版本支持Python异步（async/await）功能的社区投票

### ISSUE THREAD

**Issue by CZJCC** [nacos-group/nacos-sdk-python#175]
各位Nacos-SDK-Python用户和贡献者们，

随着Python生态中异步编程的日益普及，我们正考虑在Nacos-SDK-Python的新版本中加入对异步IO的支持，以提升在异步框架下的性能和用户体验。这一改进将要求Python 3.7及以上版本，因为async/await语法及异步IO库在这些版本中得到了完善。

为了确保这一决策能够满足大多数用户的需求，我们特此发起投票，请大家根据您的实际使用场景和期望，选择最适合的选项。您的意见对我们至关重要！

投票选项：
- 1.强烈支持：我正在使用或计划使用异步框架，希望Nacos-SDK-Python能提供原生的异步支持。
- 2.支持：虽然我当前未使用异步框架，但认为增加异步功能有利于库的长远发展，对社区有益。
- 3.中立：对我而言，同步或异步支持均可，更关注稳定性与兼容性。
- 4.不支持：我认为应该优先优化现有功能和稳定性，异步特性可能带来不必要的复杂度。
- 5.反对：我的项目依赖于Python早期版本，不希望因异步支持而提高最低Python版本要求。

注意事项：
每个GitHub账户仅限投一票。
在该议题下留言，直接回复数字序号（例如：1）表示您的选择。为保证投票的有效性，请尽量避免发表除选项数字外的其他内容。
投票有效期为7天，从发布投票之日起计算。
我们将基于投票结果和社区讨论来决定是否以及如何实施异步功能的支持。
感谢您的积极参与和宝贵意见，让我们共同推动Nacos-SDK-Python的发展！

**Comment by anjia0532** [comment]
1

**Comment by blackfishdel** [comment]
3

**Comment by xinwangu** [comment]
1

**Comment by al6nlee** [comment]
1

**Comment by ryanrain2016** [comment]
1

**Comment by wydream** [comment]
2

**Comment by GPFE05** [comment]
1

**Comment by wjshan** [comment]
1

**Comment by Vergilraven** [comment]
1

**Comment by nightosong** [comment]
2

**Comment by Abeautifulsnow** [comment]
1

**Comment by Athur6908** [comment]
1

**Comment by strong-xiaoge** [comment]
1

**Comment by icarus0329** [comment]
1

**Comment by code2tan** [comment]
1

**Comment by psxjoy** [comment]
2

**Comment by yy4ever** [comment]
1

**Comment by ruyisee** [comment]
1

**Comment by yuanpusheng** [comment]
1

**Comment by xiwang0439** [comment]
1

**Comment by yumaofan** [comment]
1

**Comment by astra-zhao** [comment]
3和4

**Comment by facioushy** [comment]
2

**Comment by Beau-xu** [comment]
1

**Comment by JiajiaHuang** [comment]
1

**Comment by imbooo** [comment]
1

**Comment by hukang08** [comment]
1

**Comment by bitjerry** [comment]
1

**Comment by raceli** [comment]
1

**Comment by CZJCC** [comment]
V2 Beta版本，欢迎大家试用

https://github.com/nacos-group/nacos-sdk-python?tab=readme-ov-file#nacos-sdk-python-v2
