### ISSUE TITLE
nacos.exception.NacosException: Insufficient privilege.

### ISSUE THREAD

**Issue by huangwei907781034** [nacos-group/nacos-sdk-python#177]
鉴权的代码，没有合并到最新版本，麻烦合并发布一下？https://github.com/nacos-group/nacos-sdk-python/pull/133

**Comment by CZJCC** [comment]
参考https://github.com/nacos-group/nacos-sdk-python/blob/ebe30647e3d9f5511f5ce4c76d79936b38401510/nacos/client.py#L346  已经有了

**Comment by huangwei907781034** [comment]
是的，有的
