### ISSUE TITLE
When calling add_config_watcher, if the user is not nacos, a 403 error will occur, and access to /nacos/v1/cs/configs/listener will be denied.

### ISSUE THREAD

**Issue by gongycn** [nacos-group/nacos-sdk-python#178]
When calling add_config_watcher, if the user is not nacos, a 403 error will occur, and access to /nacos/v1/cs/configs/listener will be denied.

**Comment by CZJCC** [comment]
What is your python sdk version and what is your usage scenario? 

I didn‘t reproduce your problem when the user is not "nacos"

**Comment by CZJCC** [comment]
or can you show your test code which can reproduce this bug?
