### ISSUE TITLE
add_naming_instance的问题

### ISSUE THREAD

**Issue by ohlsj** [nacos-group/nacos-sdk-python#27]
调用`add_naming_instance`返回500，跟踪了一下发现如下情况。

在`add_naming_instance`方法中，有一处对`_do_sync_req`的调用：
````
resp = self._do_sync_req("/nacos/v1/ns/instance", None, None, params, self.default_timeout, "POST")
````
其中第三个参数None传给了param，第四个参数params传给了data

在`_do_sync_req`中会将params放在url中，将data放在body中。

而根据nacos的api规范，参数应该放在url中。所以上面的调用会返回错误。

我的环境：
python：3.6
nacos-sdk-python: 0.1.5

**Comment by silence19841230** [comment]
@ohlsj 我也发现了同样的问题，换了位置就好了。

**Comment by samandqq** [comment]
python：3.6
nacos-sdk-python: 0.1.5
通过UT测试如何：
![image](https://user-images.githubusercontent.com/1614545/97126483-e8d5c880-1771-11eb-8468-4489afe7d80a.png)

能否把调用的参数发出来，看是否是入参的问题，谢谢！
