### ISSUE TITLE
get_configs 在命名空间为public时拿不到数据问题

### ISSUE THREAD

**Issue by ziux** [nacos-group/nacos-sdk-python#28]
/nacos/v1/cs/configs?dataId=&group=&search=accurate&pageNo=1&pageSize=1000&tenant=public&username=nacos&password=nacos
这个接口在命名空间为public时,拿不到数据
初步判断,在官方提供的管理界面上,如果为public时tenant参数应该为空,所以如果命名空间为public时,需要做特殊处理

**Comment by premier815** [comment]
> /nacos/v1/cs/configs?dataId=&group=&search=accurate&pageNo=1&pageSize=1000&tenant=public&username=nacos&password=nacos
> 这个接口在命名空间为public时,拿不到数据
> 初步判断,在官方提供的管理界面上,如果为public时tenant参数应该为空,所以如果命名空间为public时,需要做特殊处理

是你传错值了吧，namespace参数需要传命名空间对应的Namespace ID，不是传命名空间的名称，public空间对应的id是空的。代码里默认的命名空间的id就是空的。DEFAULT_NAMESPACE = "", tenant的值也取自self.namespace

**Comment by ziux** [comment]
> > /nacos/v1/cs/configs?dataId=&group=&search=accurate&pageNo=1&pageSize=1000&tenant=public&username=nacos&password=nacos
> > 这个接口在命名空间为public时,拿不到数据
> > 初步判断,在官方提供的管理界面上,如果为public时tenant参数应该为空,所以如果命名空间为public时,需要做特殊处理
> 
> 是你传错值了吧，namespace参数需要传命名空间对应的Namespace ID，不是传命名空间的名称，public空间对应的id是空的。代码里默认的命名空间的id就是空的。DEFAULT_NAMESPACE = "", tenant的值也取自self.namespace

应该是的,我没有注意默认的命名空间的id为空而不是public
