### ISSUE TITLE
集群数目为什么是2？

### ISSUE THREAD

**Issue by Orangeices** [nacos-group/nacos-sdk-python#43]
![image](https://user-images.githubusercontent.com/51935112/116332292-0e688b00-a804-11eb-881a-d72545d98b18.png)
```
def regis_server_to_nacos():
    '''
    注册到nacos
    '''
    SERVER_ADDRESSES = "xxxx"
    NAMESPACE = "xxxx"
    # 获取到本机IP
    current_host_ip = get_current_host_ip()
    # no auth mode
    client = nacos.NacosClient(SERVER_ADDRESSES, namespace=NAMESPACE)
    group = "XXXXX"
    client.add_naming_instance("ner-service", current_host_ip, "80", group_name=group)
    def nacos_client_send_heartbeat():
        client.send_heartbeat("ner-service", current_host_ip, "80", group_name=group)
    return nacos_client_send_heartbeat
```

**Comment by yangj2133** [comment]
> ![image](https://user-images.githubusercontent.com/51935112/116332292-0e688b00-a804-11eb-881a-d72545d98b18.png)
> 
> ```
> def regis_server_to_nacos():
>     '''
>     注册到nacos
>     '''
>     SERVER_ADDRESSES = "xxxx"
>     NAMESPACE = "xxxx"
>     # 获取到本机IP
>     current_host_ip = get_current_host_ip()
>     # no auth mode
>     client = nacos.NacosClient(SERVER_ADDRESSES, namespace=NAMESPACE)
>     group = "XXXXX"
>     client.add_naming_instance("ner-service", current_host_ip, "80", group_name=group)
>     def nacos_client_send_heartbeat():
>         client.send_heartbeat("ner-service", current_host_ip, "80", group_name=group)
>     return nacos_client_send_heartbeat
> ```

你指定一个cluster_name应该就行了，那2个一个是“None”一个是“DEFAULT”

**Comment by gaozhengjie** [comment]
返回的发送心跳的函数，是通过crontab设置定时任务去调用吗？

**Comment by Orangeices** [comment]
@yangj2133 
```
client.add_naming_instance("ner-service", current_host_ip, "80", group_name=group, **cluster_name='DEFAULT'**)
    def nacos_client_send_heartbeat():
        client.send_heartbeat("ner-service", current_host_ip, "80", group_name=group, **cluster_name='DEFAULT'**)
```
首先表示感谢！！
* 这样加上了，还是没变化，还是两个  ):  不过之前在服务器上跑的那个，什么都没改，**两个变成一个**了(神奇)
* 还有，`add_naming_instance`和`send_heartbeat`这两函数的第二个参数`ip`，到底是写本机的还是nacos的`SERVER_ADDRESSES`?

**Comment by Orangeices** [comment]
> 返回的发送心跳的函数，是通过crontab设置定时任务去调用吗？

**没用`crontab`**，我在程序里写的。
```
from apscheduler.schedulers.background import BackgroundScheduler
...
# BackgroundScheduler: 适合于要求任何在程序后台运行的情况，当希望调度器在应用后台执行时使用。
scheduler = BackgroundScheduler()
# 采用非阻塞的方式
# 采用固定时间间隔（interval）的方式，每隔3秒钟执行一次
scheduler.add_job(nacos_client_send_heartbeat, 'interval', seconds=3)
# 一个独立的线程
scheduler.start()
# 后面其他任务是另外独立的线程
```

**Comment by yangj2133** [comment]
> @yangj2133
> 
> ```
> client.add_naming_instance("ner-service", current_host_ip, "80", group_name=group, **cluster_name='DEFAULT'**)
>     def nacos_client_send_heartbeat():
>         client.send_heartbeat("ner-service", current_host_ip, "80", group_name=group, **cluster_name='DEFAULT'**)
> ```
> 
> 首先表示感谢！！
> 
> * 这样加上了，还是没变化，还是两个  ):  不过之前在服务器上跑的那个，什么都没改，**两个变成一个**了(神奇)
> * 还有，`add_naming_instance`和`send_heartbeat`这两函数的第二个参数`ip`，到底是写本机的还是nacos的`SERVER_ADDRESSES`?
我觉得准确点来说`add_naming_instance`和`send_heartbeat`这两函数的第二个参数`ip`是要写你python服务的ip，如果就是在本地跑的服务，就是本机ip；如果是用了docker用了桥接网络什么的，那就是服务的ip。理论上和nacos的`SERVER_ADDRESSES`应该没关系，但是如果都在同一台机器上，那就全都本机ip

**Comment by yangj2133** [comment]
> @yangj2133
> 
> ```
> client.add_naming_instance("ner-service", current_host_ip, "80", group_name=group, **cluster_name='DEFAULT'**)
>     def nacos_client_send_heartbeat():
>         client.send_heartbeat("ner-service", current_host_ip, "80", group_name=group, **cluster_name='DEFAULT'**)
> ```
> 
> 首先表示感谢！！
> 
> * 这样加上了，还是没变化，还是两个  ):  不过之前在服务器上跑的那个，什么都没改，**两个变成一个**了(神奇)
> * 还有，`add_naming_instance`和`send_heartbeat`这两函数的第二个参数`ip`，到底是写本机的还是nacos的`SERVER_ADDRESSES`?

我觉得准确点来说`add_naming_instance`和`send_heartbeat`这两函数的第二个参数`ip`是要写你python服务的ip，如果就是在本地跑的服务，就是本机ip；如果是用了docker用了桥接网络什么的，那就是服务的ip。理论上和nacos的`SERVER_ADDRESSES`应该没关系，但是如果都在同一台机器上，那就全都本机ip
