### ISSUE TITLE
Bug in add_naming_instance

### ISSUE THREAD

**Issue by Aknifejackzhmolong** [nacos-group/nacos-sdk-python#6]
## Issue Description

Type: *bug report*

### Describe what happened

Description: The NacosRequestException and 500 error are raised while the parameter filled in the function like "client.add_naming_instance(service_name='rpi-test',ip='11.11.11.11',port=8088)"

> WARNING:root:[do-sync-req] server:121.36.31.116:8848 is not available for reason:
ERROR:root:[do-sync-req] 121.36.31.116:8848 maybe down, no server is currently available
ERROR:root:[add-naming-instance] exception All server are not available occur
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/nacos/lib/python3.7/site-packages/nacos/client.py", line 581, in add_naming_instance
    resp = self._do_sync_req("/nacos/v1/ns/instance", None, None, params, self.default_timeout, "POST")
  File "/home/pi/.virtualenvs/nacos/lib/python3.7/site-packages/nacos/client.py", line 452, in _do_sync_req
    raise NacosRequestException("All server are not available")
nacos.exception.NacosRequestException: All server are not available
Traceback (most recent call last):
  File "/home/pi/Downloads/nacos/nacos-client.py", line 27, in <module>
    client.add_naming_instance(service_name='rpi-test',ip='11.11.11.11',port=8088)
  File "/home/pi/.virtualenvs/nacos/lib/python3.7/site-packages/nacos/client.py", line 581, in add_naming_instance
    resp = self._do_sync_req("/nacos/v1/ns/instance", None, None, params, self.default_timeout, "POST")
  File "/home/pi/.virtualenvs/nacos/lib/python3.7/site-packages/nacos/client.py", line 452, in _do_sync_req
    raise NacosRequestException("All server are not available")
nacos.exception.NacosRequestException: All server are not available

### How to reproduce it

Environment:
1. run in raspberry pi4B
2. run in OS like 2020-02-05-raspbian-buster-full
3. python 3.7.3
4. use function "client.add_naming_instance" with just three required parameters included service_name,ip,port

### Anything else we need to know?

It's maybe a solution:

I found it caused by "metadata" and "cluster_name" when they are None instead of ''.
it equal the comand below.
> curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?ip=11.11.11.11&port=8088&serviceName=rpi-test&weight=1.0&enable=True&healthy=True&metadata=None&clusterName=None'

And, client.add_naming_instance(service_name='rpi-test',ip='11.11.11.11',port=8088,cluster_name='',metadata='') is available

**Comment by chen0928622** [comment]
请问nacos注册服务几秒钟后就关闭，这个问题怎么解决？

**Comment by Aknifejackzhmolong** [comment]
> 请问nacos注册服务几秒钟后就关闭，这个问题怎么解决？

 在元数据metadata里添加如下内容并且每个4秒左右发送心跳就可以用了

> metadata = '{"preserved.register.source":"SPRING_CLOUD"}'

我用的是Gateway做网关用的，不知你是用在什么情景下

**Comment by chen0928622** [comment]
我是做检测任务的服务注册

**Comment by Aknifejackzhmolong** [comment]
> 我是做检测任务的服务注册

我不是这个意思。。。我是指你用的是Feign组件、Ribbon还是Gateway组件访问你的微服务。。。。
顺便一问，你使用微服务是为了分布式执行多个任务的负载均衡对吗

**Comment by chen0928622** [comment]
我这也是Gateway，是要做负载均衡

**Comment by Aknifejackzhmolong** [comment]
> 我这也是Gateway，是要做负载均衡

那你就按我上边说的方法去配置应该没问题
我用Gateway能够正常访问，就是Nacos后台时不时显示健康状态为False，但是Http不会出现突然连不上的情况

**Comment by chen0928622** [comment]
我这边已经调整完成，目前测试正常，非常感谢

**Comment by Aknifejackzhmolong** [comment]
> 我这边已经调整完成，目前测试正常，非常感谢

不客气

**Comment by silaslxy** [comment]
这个是代码默认值bug，我这边看见add_naming_instance的metadata参数默认值是None，理论上不传也可以，但是现在我这边传一个空串“”或者{} 都是可以注册服务的，而在send_heartbeat中metadata的默认值None是没有问题的
想问一下为什么metadata = '{"preserved.register.source":"SPRING_CLOUD"}'要设置为这个呢，意思是什么

**Comment by silaslxy** [comment]
也就是metadata 是必传的 要么metadata =“” 要么metadata ={}

**Comment by Aknifejackzhmolong** [comment]
> 想问一下为什么metadata = '{"preserved.register.source":"SPRING_CLOUD"}'要设置为这个呢，意思是什么

不知道，我看SpringCloud Nacos Discovery注册Nacos后，在后台中看到使用了这个metadata就跟着用了，具体为啥这么用我没看源码

**Comment by Aknifejackzhmolong** [comment]
> 也就是metadata 是必传的 要么metadata =“” 要么metadata ={}

我试过传metadata = '{"preserved.register.source":"PYTHON"}'，但完全不管用

**Comment by silaslxy** [comment]
> > 想问一下为什么metadata = '{"preserved.register.source":"SPRING_CLOUD"}'要设置为这个呢，意思是什么
> 
> 不知道，我看SpringCloud Nacos Discovery注册Nacos后，在后台中看到使用了这个metadata就跟着用了，具体为啥这么用我没看源码

脑壳痛，这里不传gateway也是可以访问服务的

**Comment by Aknifejackzhmolong** [comment]
> > > 想问一下为什么metadata = '{"preserved.register.source":"SPRING_CLOUD"}'要设置为这个呢，意思是什么
> > 
> > 
> > 不知道，我看SpringCloud Nacos Discovery注册Nacos后，在后台中看到使用了这个metadata就跟着用了，具体为啥这么用我没看源码
> 
> 脑壳痛，这里不传gateway也是可以访问服务的

我特地看了一下Nacos后台，Gateway的注册信息里也是metadata = '{"preserved.register.source":"SPRING_CLOUD"}'

**Comment by samandqq** [comment]
大家好， 目前在develop分支上做了修复, metadata同时支持metadata='{"a":"a"}' 和 metadata={"a":"a"} 和默认值None ，后续develop分支会合并到master分支，并更新到pip仓库中：

    def test_modify_naming_instance(self):
        self.assertEqual(
            client.modify_naming_instance("test.service", "1.0.0.1", 8080, cluster_name="testCluster", enable=False,
                                         metadata='{"a":"a"}'), True)

    def test_modify_naming_instance_with_dict_metadata(self):
        self.assertEqual(
            client.modify_naming_instance("test.service", "1.0.0.1", 8080, cluster_name="testCluster", enable=False,
                                          metadata={"a":"a"}), True)

**Comment by Aknifejackzhmolong** [comment]
> 大家好， 目前在develop分支上做了修复, metadata同时支持metadata='{"a":"a"}' 和 metadata={"a":"a"} 和默认值None ，后续develop分支会合并到master分支，并更新到pip仓库中：
> 
> ```
> def test_modify_naming_instance(self):
>     self.assertEqual(
>         client.modify_naming_instance("test.service", "1.0.0.1", 8080, cluster_name="testCluster", enable=False,
>                                      metadata='{"a":"a"}'), True)
> 
> def test_modify_naming_instance_with_dict_metadata(self):
>     self.assertEqual(
>         client.modify_naming_instance("test.service", "1.0.0.1", 8080, cluster_name="testCluster", enable=False,
>                                       metadata={"a":"a"}), True)
> ```

请问一下，我发现Nacos注册的时候如果不用metadata = '{"preserved.register.source":"SPRING_CLOUD"}'的话连接容易断开，而且健康状态为False，这怎么办？

**Comment by silaslxy** [comment]
你好 注册心跳 使用线程发送好呢 还是进程 ，还是在同步代码中用事件循环

**Comment by Aknifejackzhmolong** [comment]
> 你好 注册心跳 使用线程发送好呢 还是进程 ，还是在同步代码中用事件循环

随你喜欢吧。。。。。我比较菜用的线程，线程能共享参数，进程写起来麻烦，不过事件循环也得写线程里吧

**Comment by samandqq** [comment]
> > 大家好， 目前在develop分支上做了修复, metadata同时支持metadata='{"a":"a"}' 和 metadata={"a":"a"} 和默认值None ，后续develop分支会合并到master分支，并更新到pip仓库中：
> > ```
> > def test_modify_naming_instance(self):
> >     self.assertEqual(
> >         client.modify_naming_instance("test.service", "1.0.0.1", 8080, cluster_name="testCluster", enable=False,
> >                                      metadata='{"a":"a"}'), True)
> > 
> > def test_modify_naming_instance_with_dict_metadata(self):
> >     self.assertEqual(
> >         client.modify_naming_instance("test.service", "1.0.0.1", 8080, cluster_name="testCluster", enable=False,
> >                                       metadata={"a":"a"}), True)
> > ```
> 
> 请问一下，我发现Nacos注册的时候如果不用metadata = '{"preserved.register.source":"SPRING_CLOUD"}'的话连接容易断开，而且健康状态为False，这怎么办？

您好， 我查了一下nacos服务端，并没有对‘preserved.register.source’ 的值做特殊处理，连接容易断开会不会是心跳检查间隔或心跳断了有相关，我这里尝试了metadata='{"a": "b"}'， 同事设间隔3秒做一次发送实例心跳，之后查询实例和实例列表多是正常的
