### ISSUE TITLE
[Bug] Server Error with send_heartbeat()

### ISSUE THREAD

**Issue by joyatcloudfall** [nacos-group/nacos-sdk-python#96]
A bug appears while sending heartbeats. As shown below that there is an exception that no server is available. However, I believed the heartbeat was sent to the server successfully since the instance is healthy as I could see via Nacos UI. I've also tried to use the OpenAPI to send heartbeats directly. I can successfully send heartbeats to the server via API, but still got 500 as status code and there is no further information that I could monitor.
nacos-sdk-python== 0.1.6 
nacos version 2.0.4
```
URL = "http://serverIP:8848/nacos/v1/ns/instance/beat?serviceName={SERVICE_NAME}&groupName=DEFAULT_GROUP&beat=%7b%22cluster%22%3a%22DEFAULT%22%2c%22ip%22%3a%22{IP}%22%2c%22metadata%22%3a%7b%7d%2c%22port%22%3a{PORT}%2c%22scheduled%22%3atrue%2c%22ephemeral%22%3afalse%2c%22serviceName%22%3a%22{SERVICE_NAME}"%22%2c%22weight%22%3a1%7d"
response = requests.put(url=URL)
```
![image](https://user-images.githubusercontent.com/87688951/150090589-7bb9a4dd-d7c6-4398-8b47-9762e503267c.png)
![image](https://user-images.githubusercontent.com/87688951/150091153-b0e2f01b-268a-475e-b749-7b77b5bb9cba.png)

**Comment by joyatcloudfall** [comment]
This issue was solved by adding an instance as an ephemeral instance.

**Comment by SsuperL** [comment]
I got the same problem,but the default value of `ephemeral` is True.

**Comment by joyatcloudfall** [comment]
> I got the same problem,but the default value of `ephemeral` is True.

The issue is still open if the API was hosted in a Docker Container, but we suspect it is not the issue with this python SDK since everything was fine when we run API directly. So I just closed this issue and open another one in the original Nacos git repo.
